"""Geração de DDL a partir do modelo ER (Navathe 6ª Ed.) e do modelo Dimensional (Kimball).

Regras de mapeamento ER-para-Relacional (Capítulo 9 - Elmasri & Navathe):
Passo 0: Domínios definidos pelo usuário (tabela de domínio + FK, ou CHECK).
Passo 1: Entidades Regulares (atributos simples, sub-atributos de compostos; exclui derivados e multivalorados).
Passo 2: Entidades Fracas (inclui FK da proprietária; PK = FK + chave parcial; ON DELETE CASCADE).
Passo 8: Especialização/Generalização (8A: tabela por classe; tabela única com discriminador/flags).
Passo 9: Categorias (uniões) com chave substituta.
Passo 3: Relacionamentos 1:1 (FK na entidade de participação total com restrição UNIQUE + atributos do relacionamento).
Passo 4: Relacionamentos 1:N (FK no lado N + atributos do relacionamento).
Passo 5: Relacionamentos M:N (tabela associativa com PK composta das FKs + atributos do relacionamento).
Passo 6: Atributos Multivalorados (tabela separada com FK da entidade + valor do atributo formando PK composta).
Passo 7: Relacionamentos n-ários (tabela associativa com as FKs de todos os participantes).

Descrições: descrição de entidade/atributo/relacionamento vira COMMENT (MySQL: cláusula COMMENT inline;
PostgreSQL/Oracle: COMMENT ON TABLE/COLUMN). Os passos 8 e 9 são emitidos antes dos relacionamentos
(3, 4, 5, 6, 7) para que as tabelas das subclasses já existam quando as chaves estrangeiras forem criadas.
"""
import re
import zlib

TYPE_MAP = {
    "postgres": {"STRING": "VARCHAR(255)", "INTEGER": "INTEGER", "DECIMAL": "NUMERIC(12,2)",
                 "DATE": "DATE", "BOOLEAN": "BOOLEAN", "TEXT": "TEXT"},
    "mysql": {"STRING": "VARCHAR(255)", "INTEGER": "INT", "DECIMAL": "DECIMAL(12,2)",
              "DATE": "DATE", "BOOLEAN": "TINYINT(1)", "TEXT": "TEXT"},
    "oracle": {"STRING": "VARCHAR2(255)", "INTEGER": "NUMBER(10)", "DECIMAL": "NUMBER(12,2)",
               "DATE": "DATE", "BOOLEAN": "NUMBER(1)", "TEXT": "CLOB"},
}

# Comprimento máximo de identificador por dialeto.
MAX_IDENT_LEN = {"postgres": 63, "mysql": 64, "oracle": 128}


def map_type(dialect, t):
    table = TYPE_MAP.get(dialect, TYPE_MAP["postgres"])
    return table.get(t, table["STRING"])


def sanitize(name, dialect="postgres"):
    """Converte um nome do modelo em identificador SQL (minúsculo, sem acentos/espaços).

    Nomes longos são truncados com sufixo CRC32 (estável entre execuções, ao contrário de hash())."""
    if not name:
        return ""
    import unicodedata
    base = unicodedata.normalize("NFKD", str(name).strip())
    base = "".join(ch for ch in base if not unicodedata.combining(ch))
    ident = base.replace(" ", "_").lower()
    ident = "".join(ch if (ch.isalnum() and ch.isascii()) or ch == "_" else "_" for ch in ident)
    if ident and ident[0].isdigit():
        ident = "_" + ident
    max_len = MAX_IDENT_LEN.get(dialect, 63)
    if len(ident) > max_len:
        suffix = format(zlib.crc32(ident.encode("utf-8")) % 10_000, "04d")
        ident = f"{ident[:max_len - 5]}_{suffix}"
    return ident


def sql_str(text, dialect="postgres"):
    """Literal string SQL seguro (aspas duplicadas; barra invertida escapada no MySQL)."""
    t = " ".join(str(text).split()).replace("'", "''")
    if dialect == "mysql":
        t = t.replace("\\", "\\\\")
    return "'" + t + "'"


def identity_clause(dialect, col_type):
    """Chave substituta auto-incremental (PostgreSQL 10+ / Oracle 12c+ usam SQL:2008)."""
    if dialect in ("postgres", "oracle"):
        return f"{col_type} GENERATED BY DEFAULT AS IDENTITY"
    if dialect == "mysql":
        return f"{col_type} AUTO_INCREMENT"
    return col_type


def index_stmt(dialect, table, cols, idx_name):
    return f"CREATE INDEX {idx_name} ON {table} ({', '.join(cols)});"


def drop_schema_hint(dialect):
    if dialect == "postgres":
        return ("-- Para recriar o esquema do zero (PostgreSQL):\n"
                "--   DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
    if dialect == "oracle":
        return "-- A opção comentada para recriar o esquema do zero aparece logo abaixo."
    return "-- Para recriar o esquema do zero (MySQL): DROP DATABASE IF EXISTS <db>; CREATE DATABASE <db>;"


def _flat(text):
    return " ".join(str(text or "").split())


class _Ctx:
    """Estado da geração: resolve nomes/chaves, evita colisões e emite CREATE/ALTER com comentários."""

    def __init__(self, project, dialect):
        self.p = project
        self.d = dialect
        self.out = []
        self.used = {}          # tabela -> colunas já declaradas
        self.tables = []        # tabelas criadas (ordem)
        self.domain_tables = {}  # domain.id -> nome da tabela de domínio
        self.rel_fks = {}       # (tabela, rel_id) -> lista de nomes de colunas FK

    # ---------- nomes ----------
    def s(self, name):
        return sanitize(name, self.d)

    def cname(self, *parts):
        return sanitize("_".join(p for p in parts if p), self.d)

    def t(self, ent):
        """Tabela física da entidade (subclasses de tabela única vivem na tabela da superclasse)."""
        spec = self.p.spec_of_child(ent.id)
        if spec and not spec.is_union and spec.mapping == "single":
            parent = self.p.find_entity(spec.parent_ids[0])
            if parent and parent.id != ent.id:
                return self.t(parent)
        return self.s(ent.name)

    def _own_key_attrs(self, ent):
        keys = ent.pk_attrs()
        if not keys:
            fb = ent.pk_attr()
            keys = [fb] if fb else []
        return keys

    def key_cols(self, ent, _seen=None):
        """Colunas da chave [(coluna, tipo_modelo)]; subclasses herdam a chave da superclasse."""
        _seen = _seen or set()
        if ent.id in _seen:
            return []
        _seen.add(ent.id)
        spec = self.p.spec_of_child(ent.id)
        if spec and not spec.is_union:
            parent = self.p.find_entity(spec.parent_ids[0])
            if parent:
                return self.key_cols(parent, _seen)
        if spec and spec.is_union:
            if ent.pk_attrs():
                pass
            else:
                return [(f"{self.s(ent.name)}_sk", "INTEGER")]
        res = []
        for a in self._own_key_attrs(ent):
            if a.is_composite and a.sub_attrs:
                res.extend((f"{self.s(a.name)}_{self.s(sub.name)}", sub.type) for sub in a.sub_attrs)
            else:
                res.append((self.s(a.name), self.attr_type(a)))
        return res

    def fk_cols(self, prefix, key_columns):
        return [(f"{prefix}_{c}", c, typ) for c, typ in key_columns]

    def unique_fk(self, table, prefix, keys, rel_name):
        """Colunas FK sem colidir com colunas existentes (usa o nome do relacionamento se preciso)."""
        pairs = self.fk_cols(prefix, keys)
        used = self.used.get(table, set())
        if any(fk in used for fk, _, _ in pairs):
            pairs = self.fk_cols(f"{self.s(rel_name)}_{prefix}", keys)
        return pairs

    # ---------- tipos, domínios ----------
    def domain_of(self, a):
        return self.p.find_domain(a.domain_id) if getattr(a, "domain_id", None) else None

    def attr_type(self, a):
        dom = self.domain_of(a)
        return dom.type if dom else a.type

    def comment_of(self, a, parent=None):
        parts = []
        if a.description:
            parts.append(_flat(a.description))
        elif parent is not None and parent.description:
            parts.append(f"{_flat(parent.description)} ({a.name})")
        dom = self.domain_of(a)
        if dom:
            parts.append(f"Domínio {dom.name}: {dom.summary()}" if dom.values else f"Domínio {dom.name}")
        return " | ".join(parts)

    def attr_constraints(self, table, col, a):
        """CHECK / FK de domínio e UNIQUE de um atributo (strings de constraint inline)."""
        cons = []
        dom = self.domain_of(a)
        if dom:
            if dom.impl == "lookup":
                cons.append(f"CONSTRAINT {self.cname('fk', table, col, 'dom')} FOREIGN KEY ({col}) "
                            f"REFERENCES {self.domain_table(dom)}(codigo)")
            elif dom.values:
                lits = ", ".join(dom.sql_literal(v["code"]) for v in dom.values)
                cons.append(f"CONSTRAINT {self.cname('ck', table, col)} CHECK ({col} IN ({lits}))")
        if a.unique and not a.is_pk:
            cons.append(f"CONSTRAINT {self.cname('uq', table, col)} UNIQUE ({col})")
        return cons

    def domain_table(self, dom):
        return self.domain_tables.setdefault(dom.id, self.cname("dom", dom.name))

    # ---------- emissão ----------
    def column(self, name, sql_type, nn=False, comment="", extra=""):
        return {"name": name, "type": sql_type, "nn": nn, "comment": comment, "extra": extra}

    def _col_sql(self, c):
        ln = f"{c['name']} {c['type']}"
        if c.get("extra"):
            ln += f" {c['extra']}"
        if c["nn"]:
            ln += " NOT NULL"
        if self.d == "mysql" and c["comment"]:
            ln += f" COMMENT {sql_str(c['comment'], self.d)}"
        return ln

    def _comment_stmts(self, table, cols, table_comment=""):
        if self.d == "mysql":
            return []
        stmts = []
        if table_comment:
            stmts.append(f"COMMENT ON TABLE {table} IS {sql_str(table_comment, self.d)};")
        for c in cols:
            if c["comment"]:
                stmts.append(f"COMMENT ON COLUMN {table}.{c['name']} IS {sql_str(c['comment'], self.d)};")
        return stmts

    def create_table(self, table, cols, constraints=(), comment="", pre_comments=()):
        lines = [f"  {self._col_sql(c)}" for c in cols] + [f"  {k}" for k in constraints]
        sql = "\n".join(pre_comments)
        sql = (sql + "\n" if sql else "") + f"CREATE TABLE {table} (\n" + ",\n".join(lines) + "\n)"
        if self.d == "mysql" and comment:
            sql += f" COMMENT={sql_str(comment, self.d)}"
        sql += ";"
        self.out.append(sql)
        cm = self._comment_stmts(table, cols, comment)
        if cm:
            self.out.extend(cm)
        self.out.append("")
        self.used.setdefault(table, set()).update(c["name"] for c in cols)
        self.tables.append(table)

    def add_column(self, table, col):
        """ALTER TABLE ... ADD [COLUMN] (com comentário)."""
        col_def = self._col_sql(col)
        if self.d == "oracle":
            self.out.append(f"ALTER TABLE {table} ADD ({col_def});")
        else:
            self.out.append(f"ALTER TABLE {table} ADD COLUMN {col_def};")
        self.out.extend(self._comment_stmts(table, [col]))
        self.used.setdefault(table, set()).add(col["name"])

    def add_constraint(self, table, constraint):
        self.out.append(f"ALTER TABLE {table} ADD {constraint};")

    def alter_constraints_for(self, table, col, a):
        for k in self.attr_constraints(table, col, a):
            self.add_constraint(table, k)

    def columns_of(self, ent, force_pk_kind="pk", skip_pk_flag=False):
        """Colunas persistidas da entidade: (lista_cols, lista_pk, lista_constraints, comentários SQL)."""
        cols, pks, cons, notes = [], [], [], []
        table = self.s(ent.name)
        for a in ent.attrs:
            if a.is_derived:
                notes.append(f"-- Atributo derivado '{a.name}': calculado dinamicamente (não persistido)")
                continue
            if a.is_multivalued:
                notes.append(f"-- Atributo multivalorado '{a.name}': mapeado para tabela própria (Passo 6)")
                continue
            is_key = (a.attr_type == force_pk_kind) and not skip_pk_flag
            if a.is_composite and a.sub_attrs:
                grp = []
                for sub in a.sub_attrs:
                    cn = f"{self.s(a.name)}_{self.s(sub.name)}"
                    cols.append(self.column(cn, map_type(self.d, self.attr_type(sub)),
                                            sub.nn or is_key, self.comment_of(sub, a)))
                    grp.append(cn)
                    if is_key:
                        pks.append(cn)
                    cons.extend(self.attr_constraints(table, cn, sub) if not a.unique else [])
                if a.unique and not is_key and grp:
                    cons.append(f"CONSTRAINT {self.cname('uq', table, *grp[:1])} UNIQUE ({', '.join(grp)})")
                continue
            cn = self.s(a.name)
            cols.append(self.column(cn, map_type(self.d, self.attr_type(a)), a.nn or is_key, self.comment_of(a)))
            if is_key:
                pks.append(cn)
            cons.extend(self.attr_constraints(table, cn, a) if not is_key else
                        [k for k in self.attr_constraints(table, cn, a) if "UNIQUE" not in k])
        return cols, pks, cons, notes

    # ---------- domínios ----------
    def emit_domains(self, only_ids=None):
        doms = [d for d in self.p.domains if only_ids is None or d.id in only_ids]
        if not doms:
            return
        lookups = [d for d in doms if d.impl == "lookup"]
        if not lookups:
            return
        self.out.append("-- Passo 0: Tabelas de Domínio (valores definidos pelo usuário)")
        for d in lookups:
            tbl = self.domain_table(d)
            has_detail = any(v.get("description") for v in d.values)
            cols = [self.column("codigo", map_type(self.d, d.type), True, "Código do valor do domínio"),
                    self.column("descricao", map_type(self.d, "STRING"), True, "Descrição do valor")]
            if has_detail:
                cols.append(self.column("detalhe", map_type(self.d, "STRING"), False, "Detalhamento do valor"))
            self.create_table(tbl, cols, [f"CONSTRAINT {self.cname('pk', tbl)} PRIMARY KEY (codigo)"],
                              comment=_flat(d.description) or f"Domínio {d.name}")
            for v in d.values:
                names = "codigo, descricao" + (", detalhe" if has_detail else "")
                vals = f"{d.sql_literal(v['code'])}, {sql_str(v['label'], self.d)}"
                if has_detail:
                    vals += ", " + (sql_str(v["description"], self.d) if v.get("description") else "NULL")
                self.out.append(f"INSERT INTO {tbl} ({names}) VALUES ({vals});")
            self.out.append("")


def _used_domain_ids(project, entities):
    ids = set()
    def walk(attrs):
        for a in attrs:
            if a.domain_id:
                ids.add(a.domain_id)
            walk(a.sub_attrs)
    for e in entities:
        walk(e.attrs)
    return ids


def generate_ddl(project, dialect="postgres"):
    """Gera script DDL completo conforme as regras de mapeamento do livro de Navathe."""
    if dialect not in TYPE_MAP:
        raise ValueError(f"Dialeto não suportado: {dialect}")

    c = _Ctx(project, dialect)
    s = c.s
    out = c.out
    out.append("-- ========================================================")
    out.append("-- DDL gerado pelo Modelador ER (Notação de Chen - Navathe 6ª Ed.)")
    out.append(f"-- Dialeto: {dialect.upper()}")
    out.append("-- ========================================================")
    out.append(drop_schema_hint(dialect))
    out.append("")

    identifying_rels = [r for r in project.rels if r.is_identifying and not r.is_nary]
    child_ids = {i for sp in project.specs for i in sp.child_ids}

    # Passo 0 — domínios
    c.emit_domains()

    # Passo 1 — entidades fortes (subclasses/categorias são tratadas nos passos 8 e 9)
    out.append("-- Passo 1: Tabelas para Entidades Fortes (Regulares)")
    strong = [e for e in project.entities if not e.is_weak and e.id not in child_ids]
    weak = [e for e in project.entities if e.is_weak and e.id not in child_ids]
    for e in strong:
        cols, pks, cons, notes = c.columns_of(e, "pk")
        single_int = None
        key_attrs = [a for a in e.attrs if a.is_pk]
        if len(key_attrs) == 1 and not key_attrs[0].is_composite and c.attr_type(key_attrs[0]) == "INTEGER" \
                and not key_attrs[0].domain_id:
            single_int = s(key_attrs[0].name)
        for col in cols:
            if single_int and col["name"] == single_int:
                col["type"] = identity_clause(dialect, col["type"])
        tbl = s(e.name)
        constraints = ([f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({', '.join(pks)})"] if pks else []) + cons
        c.create_table(tbl, cols, constraints, comment=_flat(e.description), pre_comments=notes)

    # Passo 2 — entidades fracas
    if weak:
        out.append("-- Passo 2: Tabelas para Entidades Fracas (Chave Parcial + FK da Proprietária)")
        for w in weak:
            rel_ident = next((r for r in identifying_rels if w.id in (r.entity1_id, r.entity2_id)), None)
            owner = None
            if rel_ident:
                owner_id = rel_ident.entity1_id if rel_ident.entity2_id == w.id else rel_ident.entity2_id
                owner = project.find_entity(owner_id)
            cols, pks = [], []
            owner_pairs = []
            if owner:
                owner_pairs = c.fk_cols(s(owner.name), c.key_cols(owner))
                for fk_col, ref_col, key_type in owner_pairs:
                    cols.append(c.column(fk_col, map_type(dialect, key_type), True,
                                         f"FK para {c.t(owner)}.{ref_col} (entidade proprietária)"))
                    pks.append(fk_col)
            wcols, wpks, wcons, notes = c.columns_of(w, "partial_key")
            cols += wcols
            pks += wpks
            tbl = s(w.name)
            constraints = ([f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({', '.join(pks)})"] if pks else []) + wcons
            if owner_pairs:
                constraints.append(
                    f"CONSTRAINT {c.cname('fk', tbl, s(owner.name))} FOREIGN KEY ({', '.join(f for f, _, _ in owner_pairs)}) "
                    f"REFERENCES {c.t(owner)}({', '.join(r for _, r, _ in owner_pairs)}) ON DELETE CASCADE")
            c.create_table(tbl, cols, constraints, comment=_flat(w.description),
                           pre_comments=notes)
            if owner_pairs:
                out.append(index_stmt(dialect, tbl, [f for f, _, _ in owner_pairs],
                                      c.cname("idx", tbl, owner_pairs[0][0])))
        out.append("")

    # Passo 8 — especialização / generalização
    plain_specs = [sp for sp in project.specs if not sp.is_union]
    if plain_specs:
        out.append("-- Passo 8: Especialização / Generalização (executado antes dos relacionamentos)")
    for sp in plain_specs:
        parent = project.find_entity(sp.parent_ids[0]) if sp.parent_ids else None
        subs = [project.find_entity(i) for i in sp.child_ids]
        subs = [x for x in subs if x]
        if not parent or not subs:
            continue
        ptbl = c.t(parent)
        restr = f"{'disjunta' if sp.disjointness == 'd' else 'sobreposta'}, {'total' if sp.completeness == 'total' else 'parcial'}"
        if sp.mapping == "single":
            out.append(f"-- {sp.label()} de '{parent.name}' ({restr}) — tabela única em {ptbl}")
            disc = None
            if sp.disjointness == "d":
                if sp.defining_attr and any(a.name == sp.defining_attr for a in parent.attrs):
                    disc = s(sp.defining_attr)
                    out.append(f"-- Discriminador: atributo definidor '{sp.defining_attr}' já existente")
                else:
                    disc = f"{s(parent.name)}_tipo"
                    lits = ", ".join(sql_str(x.name.upper(), dialect) for x in subs)
                    c.add_column(ptbl, c.column(disc, map_type(dialect, "STRING"), False,
                                                f"Tipo (subclasse) — {sp.label()}"))
                    c.add_constraint(ptbl, f"CONSTRAINT {c.cname('ck', ptbl, disc)} CHECK ({disc} IN ({lits}))")
            else:
                for x in subs:
                    flag = f"is_{s(x.name)}"
                    c.add_column(ptbl, c.column(flag, map_type(dialect, "BOOLEAN"), False,
                                                f"Indica se o registro pertence à subclasse {x.name}"))
            for x in subs:
                cols, _pks, cons, _n = c.columns_of(x, "pk", skip_pk_flag=True)
                for col in cols:
                    col["nn"] = False   # pode ser nulo para linhas de outras subclasses
                    col["comment"] = (col["comment"] + " | " if col["comment"] else "") + f"Específico de {x.name}"
                    c.add_column(ptbl, col)
                for k in cons:
                    if "UNIQUE" not in k:
                        c.add_constraint(ptbl, k)
            out.append("")
        else:
            out.append(f"-- {sp.label()} de '{parent.name}' ({restr}) — uma tabela por classe (8A)")
            pk_pairs = c.key_cols(parent)
            for x in subs:
                tbl = s(x.name)
                cols = [c.column(col, map_type(dialect, typ), True, f"PK/FK herdada de {ptbl}.{col}")
                        for col, typ in pk_pairs]
                xcols, _pks, xcons, notes = c.columns_of(x, "pk", skip_pk_flag=True)
                cols += xcols
                pk_names = [col for col, _ in pk_pairs]
                constraints = [f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({', '.join(pk_names)})",
                               f"CONSTRAINT {c.cname('fk', tbl, ptbl)} FOREIGN KEY ({', '.join(pk_names)}) "
                               f"REFERENCES {ptbl}({', '.join(pk_names)}) ON DELETE CASCADE"] + xcons
                c.create_table(tbl, cols, constraints,
                               comment=_flat(x.description) or f"Subclasse de {parent.name}",
                               pre_comments=notes)
    if plain_specs:
        out.append("")

    # Passo 9 — categorias (uniões)
    unions = [sp for sp in project.specs if sp.is_union]
    if unions:
        out.append("-- Passo 9: Categorias (uniões) — chave substituta + FK em cada superclasse")
    for sp in unions:
        cat = project.find_entity(sp.child_ids[0]) if sp.child_ids else None
        parents = [x for x in (project.find_entity(i) for i in sp.parent_ids) if x]
        if not cat or not parents:
            continue
        tbl = s(cat.name)
        cols, pks, cons, notes = c.columns_of(cat, "pk")
        if not pks:
            sk = f"{s(cat.name)}_sk"
            cols.insert(0, c.column(sk, identity_clause(dialect, map_type(dialect, "INTEGER")), True,
                                    f"Chave substituta da categoria {cat.name}"))
            pks = [sk]
        c.create_table(tbl, cols, [f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({', '.join(pks)})"] + cons,
                       comment=_flat(cat.description) or f"Categoria (união) de: {', '.join(x.name for x in parents)}",
                       pre_comments=notes)
        for par in parents:
            ptbl = c.t(par)
            for col in pks:
                cname_ = f"{col}" if len(parents) == 1 else f"{col}"
                ctype = next(x for x in cols if x["name"] == col)["type"].split(" GENERATED")[0].replace(" AUTO_INCREMENT", "")
                c.add_column(ptbl, c.column(cname_, ctype, False, f"FK para a categoria {cat.name}"))
            c.add_constraint(ptbl, f"CONSTRAINT {c.cname('fk', ptbl, tbl)} FOREIGN KEY ({', '.join(pks)}) "
                                   f"REFERENCES {tbl}({', '.join(pks)})")
    if unions:
        out.append("")

    # Passos 3 e 4 — 1:1 e 1:N
    out.append("-- Passos 3 e 4: Chaves Estrangeiras para Relacionamentos 1:1 e 1:N")
    for r in project.rels:
        if r.is_identifying or r.is_nary:
            continue
        e1, e2 = project.find_entity(r.entity1_id), project.find_entity(r.entity2_id)
        if not e1 or not e2:
            continue
        if not c.key_cols(e1) or not c.key_cols(e2):
            continue
        c1, c2 = r.card1.upper(), r.card2.upper()
        rel_note = f" — {_flat(r.description)}" if r.description else ""

        if c1 == "1" and c2 == "1":
            target, ref = (e2, e1) if r.part2 == "total" else (e1, e2)
            ttbl = c.t(target)
            fk_pairs = c.unique_fk(ttbl, f"{s(r.name)}_{s(ref.name)}", c.key_cols(ref), r.name)
            out.append(f"-- Relacionamento 1:1 '{r.name}' entre {e1.name} e {e2.name}")
            for fk, ref_col, ftype in fk_pairs:
                c.add_column(ttbl, c.column(fk, map_type(dialect, ftype), False,
                                            f"FK para {c.t(ref)}.{ref_col} (relacionamento {r.name}){rel_note}"))
            fks = ", ".join(f for f, _, _ in fk_pairs)
            c.rel_fks[(ttbl, r.id)] = [f for f, _, _ in fk_pairs]
            c.add_constraint(ttbl, f"CONSTRAINT {c.cname('uq', ttbl, fk_pairs[0][0])} UNIQUE ({fks})")
            c.add_constraint(ttbl, f"CONSTRAINT {c.cname('fk', ttbl, r.name)} FOREIGN KEY ({fks}) "
                                   f"REFERENCES {c.t(ref)}({', '.join(x for _, x, _ in fk_pairs)})")
            for ra in r.attrs:
                col = s(ra.name)
                c.add_column(ttbl, c.column(col, map_type(dialect, c.attr_type(ra)), False, c.comment_of(ra)))
                c.alter_constraints_for(ttbl, col, ra)
            out.append("")

        elif (c1 == "1" and c2 in ("N", "M")) or (c2 == "1" and c1 in ("N", "M")):
            if c1 == "1":
                one_ent, many_ent, one_role, many_part = e1, e2, r.role1, r.part2
            else:
                one_ent, many_ent, one_role, many_part = e2, e1, r.role2, r.part1
            recursive = e1.id == e2.id
            prefix = (s(one_role) if one_role else "supervisor") if recursive else s(one_ent.name)
            mtbl = c.t(many_ent)
            fk_pairs = c.unique_fk(mtbl, prefix, c.key_cols(one_ent), r.name)
            nn = many_part == "total"
            out.append(f"-- Relacionamento 1:N '{r.name}' entre {one_ent.name} (1) e {many_ent.name} (N)")
            for fk, ref_col, ftype in fk_pairs:
                c.add_column(mtbl, c.column(fk, map_type(dialect, ftype), nn,
                                            f"FK para {c.t(one_ent)}.{ref_col} (relacionamento {r.name}){rel_note}"))
            fks = ", ".join(f for f, _, _ in fk_pairs)
            c.rel_fks[(mtbl, r.id)] = [f for f, _, _ in fk_pairs]
            c.add_constraint(mtbl, f"CONSTRAINT {c.cname('fk', mtbl, r.name, fk_pairs[0][0])} FOREIGN KEY ({fks}) "
                                   f"REFERENCES {c.t(one_ent)}({', '.join(x for _, x, _ in fk_pairs)})")
            out.append(index_stmt(dialect, mtbl, [f for f, _, _ in fk_pairs], c.cname("idx", mtbl, fk_pairs[0][0])))
            for ra in r.attrs:
                col = s(ra.name)
                c.add_column(mtbl, c.column(col, map_type(dialect, c.attr_type(ra)), False, c.comment_of(ra)))
                c.alter_constraints_for(mtbl, col, ra)
            out.append("")

    # Passo 4.1 — Arcos de Relacionamento (Oracle Designer / Notação de Barker)
    arcs = getattr(project, "arcs", [])
    if arcs:
        out.append("-- Passo 4.1: Restrições de Arcos de Relacionamento (Exclusividade Mútua / Oracle Designer)")
        for arc in arcs:
            ent = project.find_entity(arc.entity_id)
            if not ent:
                continue
            tbl = c.t(ent)
            # Para cada relacionamento do arco, descobre a primeira coluna FK presente na tabela da entidade
            fk_cols_per_rel = []
            for rid in arc.rel_ids:
                fks = c.rel_fks.get((tbl, rid))
                if fks:
                    fk_cols_per_rel.append(fks[0])
            if len(fk_cols_per_rel) >= 2:
                arc_name = arc.name or f"arc_{ent.name}"
                c_name = c.cname("ck", tbl, arc_name, arc.id[:6] if hasattr(arc, "id") and arc.id else "")
                terms = [f"(CASE WHEN {col} IS NOT NULL THEN 1 ELSE 0 END)" for col in fk_cols_per_rel]
                sum_expr = " + ".join(terms)
                op = "= 1" if arc.mandatory else "<= 1"
                desc = "obrigatório (exatamente um)" if arc.mandatory else "opcional (no máximo um)"
                c.add_constraint(tbl, f"CONSTRAINT {c_name} CHECK ({sum_expr} {op})")
                out.append(f"-- Arco '{arc_name}' em {ent.name} ({desc}): restrição {c_name}")
        out.append("")

    # Passo 5 — M:N
    out.append("-- Passo 5: Tabelas Associativas para Relacionamentos M:N")
    for r in project.rels:
        if r.is_identifying or r.is_nary:
            continue
        if r.card1.upper() in ("M", "N") and r.card2.upper() in ("M", "N"):
            e1, e2 = project.find_entity(r.entity1_id), project.find_entity(r.entity2_id)
            if not e1 or not e2 or not c.key_cols(e1) or not c.key_cols(e2):
                continue
            jt = s(r.name) if r.name != "relaciona" else f"{s(e1.name)}_{s(e2.name)}"
            p1, p2 = s(e1.name), s(e2.name)
            if e1.id == e2.id:
                p1 = f"{s(e1.name)}_{s(r.role1) or '1'}"
                p2 = f"{s(e2.name)}_{s(r.role2) or '2'}"
            c1p, c2p = c.fk_cols(p1, c.key_cols(e1)), c.fk_cols(p2, c.key_cols(e2))
            cols = [c.column(fk, map_type(dialect, typ), True, f"FK para {c.t(ent)}.{ref}")
                    for pairs, ent in ((c1p, e1), (c2p, e2)) for fk, ref, typ in pairs]
            cons = []
            for ra in r.attrs:
                col = s(ra.name)
                cols.append(c.column(col, map_type(dialect, c.attr_type(ra)), False, c.comment_of(ra)))
                cons.extend(c.attr_constraints(jt, col, ra))
            allfk = [x[0] for x in c1p + c2p]
            constraints = [f"CONSTRAINT {c.cname('pk', jt)} PRIMARY KEY ({', '.join(allfk)})",
                           f"CONSTRAINT {c.cname('fk', jt, p1)} FOREIGN KEY ({', '.join(x[0] for x in c1p)}) "
                           f"REFERENCES {c.t(e1)}({', '.join(x[1] for x in c1p)})",
                           f"CONSTRAINT {c.cname('fk', jt, p2)} FOREIGN KEY ({', '.join(x[0] for x in c2p)}) "
                           f"REFERENCES {c.t(e2)}({', '.join(x[1] for x in c2p)})"] + cons
            c.create_table(jt, cols, constraints,
                           comment=_flat(r.description) or f"Relacionamento M:N {r.name} entre {e1.name} e {e2.name}")
            out.append(index_stmt(dialect, jt, [x[0] for x in c2p], c.cname("idx", jt, c2p[0][0])))
    out.append("")

    # Passo 6 — multivalorados
    out.append("-- Passo 6: Tabelas para Atributos Multivalorados")
    for e in project.entities:
        keys = c.key_cols(e)
        if not keys:
            continue
        for a in e.attrs:
            if not a.is_multivalued:
                continue
            etbl = c.t(e)
            tbl = f"{etbl}_{s(a.name)}"
            val_col = s(a.name)
            fk_pairs = c.fk_cols(etbl, keys)
            cols = [c.column(fk, map_type(dialect, typ), True, f"FK para {etbl}.{ref}") for fk, ref, typ in fk_pairs]
            cols.append(c.column(val_col, map_type(dialect, c.attr_type(a)), True, c.comment_of(a)))
            fk_names = [p[0] for p in fk_pairs]
            constraints = [f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({', '.join(fk_names + [val_col])})",
                           f"CONSTRAINT {c.cname('fk', tbl, etbl)} FOREIGN KEY ({', '.join(fk_names)}) "
                           f"REFERENCES {etbl}({', '.join(p[1] for p in fk_pairs)}) ON DELETE CASCADE"]
            constraints += [k for k in c.attr_constraints(tbl, val_col, a) if "UNIQUE" not in k]
            c.create_table(tbl, cols, constraints, comment=f"Valores multivalorados de {e.name}.{a.name}")

    # Passo 7 — n-ários
    nary = [r for r in project.rels if r.is_nary]
    if nary:
        out.append("-- Passo 7: Tabelas Associativas para Relacionamentos n-ários")
    for r in nary:
        parts = []
        for eid, card, part, role in r.participants():
            ent = project.find_entity(eid)
            if ent and c.key_cols(ent):
                parts.append((ent, str(card).upper(), role))
        if len(parts) < 3:
            continue
        jt = s(r.name)
        counts = {}
        cols, fk_defs, key_fk = [], [], []
        for ent, card, role in parts:
            base = s(role) if role else s(ent.name)
            counts[base] = counts.get(base, 0) + 1
            prefix = base if counts[base] == 1 else f"{base}{counts[base]}"
            pairs = c.fk_cols(prefix, c.key_cols(ent))
            for fk, ref, typ in pairs:
                cols.append(c.column(fk, map_type(dialect, typ), True, f"FK para {c.t(ent)}.{ref}"))
            fk_defs.append((ent, prefix, pairs))
            if card != "1":
                key_fk += [p[0] for p in pairs]
        if len(key_fk) < 2:
            key_fk = [p[0] for _, _, pairs in fk_defs for p in pairs]
        cons_extra = []
        for ra in r.attrs:
            col = s(ra.name)
            cols.append(c.column(col, map_type(dialect, c.attr_type(ra)), False, c.comment_of(ra)))
            cons_extra.extend(c.attr_constraints(jt, col, ra))
        constraints = [f"CONSTRAINT {c.cname('pk', jt)} PRIMARY KEY ({', '.join(key_fk)})"]
        for ent, prefix, pairs in fk_defs:
            constraints.append(f"CONSTRAINT {c.cname('fk', jt, prefix)} FOREIGN KEY ({', '.join(p[0] for p in pairs)}) "
                               f"REFERENCES {c.t(ent)}({', '.join(p[1] for p in pairs)})")
        c.create_table(jt, cols, constraints + cons_extra,
                       comment=_flat(r.description) or f"Relacionamento {len(parts)}-ário {r.name}: "
                                                       + ", ".join(p[0].name for p in parts))
        for ent, prefix, pairs in fk_defs[1:]:
            out.append(index_stmt(dialect, jt, [p[0] for p in pairs], c.cname("idx", jt, pairs[0][0])))
    if nary:
        out.append("")

    ddl = "\n".join(out)
    if dialect == "oracle":
        created = re.findall(r"CREATE TABLE\s+([A-Za-z0-9_]+)\s*\(", ddl, re.IGNORECASE)
        drop_option = ["-- OPCIONAL: para recriar o esquema do zero, descomente e execute estas linhas primeiro.",
                       "-- A ordem inversa reduz conflitos de dependência entre chaves estrangeiras."]
        drop_option.extend(f"-- DROP TABLE {t} CASCADE CONSTRAINTS PURGE;" for t in reversed(created))
        drop_option.append("")
        header_end = ddl.find("\n\n")
        ddl = ddl[:header_end + 2] + "\n".join(drop_option) + ddl[header_end + 2:]
    return ddl


# ===================================================================
# MODELAGEM DIMENSIONAL (KIMBALL) — Esquema Estrela
# ===================================================================

SCD2_COLUMNS = {
    "postgres": [("dt_inicio_validade", "DATE NOT NULL"), ("dt_fim_validade", "DATE"),
                 ("fl_versao_atual", "BOOLEAN NOT NULL DEFAULT TRUE"), ("nr_versao", "INTEGER NOT NULL DEFAULT 1")],
    "oracle": [("dt_inicio_validade", "DATE NOT NULL"), ("dt_fim_validade", "DATE"),
               ("fl_versao_atual", "NUMBER(1) DEFAULT 1 NOT NULL"), ("nr_versao", "NUMBER(10) DEFAULT 1 NOT NULL")],
    "mysql": [("dt_inicio_validade", "DATE NOT NULL"), ("dt_fim_validade", "DATE"),
              ("fl_versao_atual", "TINYINT(1) NOT NULL DEFAULT 1"), ("nr_versao", "INT NOT NULL DEFAULT 1")],
}
SCD2_COMMENTS = {
    "dt_inicio_validade": "Início de vigência da versão (SCD Tipo 2)",
    "dt_fim_validade": "Fim de vigência da versão (nulo = versão vigente)",
    "fl_versao_atual": "Indica a versão atual do registro",
    "nr_versao": "Número sequencial da versão",
}


def _flatten_regular_attrs(ctx, entity):
    """[(coluna, tipo_sql, not_null, atributo, comentário, sub_or_attr)] para atributos persistíveis."""
    cols = []
    for a in entity.attrs:
        if a.is_derived or a.is_multivalued:
            continue
        if a.is_composite and a.sub_attrs:
            for sub in a.sub_attrs:
                cols.append((f"{ctx.s(a.name)}_{ctx.s(sub.name)}", map_type(ctx.d, ctx.attr_type(sub)),
                             sub.nn, a, ctx.comment_of(sub, a), sub))
            continue
        cols.append((ctx.s(a.name), map_type(ctx.d, ctx.attr_type(a)), a.nn, a, ctx.comment_of(a), a))
    return cols


def generate_kimball_ddl(project, dialect="postgres"):
    """Gera DDL de esquema estrela (Kimball) a partir das entidades marcadas como
    'dimension' ou 'fact' (Entity.kimball_role).

    - Dimensões -> `dim_<nome>` com chave substituta `<nome>_sk` (identity), colunas naturais e,
      para SCD Tipo 2, colunas de controle de histórico.
    - Fatos -> `fat_<nome>` com uma FK `<dim>_sk` por dimensão relacionada (via relacionamentos ER)
      e as métricas (atributos numéricos) do fato.
    Descrições e domínios dos atributos são levados para o DDL como no modelo relacional.
    """
    if dialect not in TYPE_MAP:
        raise ValueError(f"Dialeto não suportado: {dialect}")
    c = _Ctx(project, dialect)
    s = c.s
    out = c.out
    dims = [e for e in project.entities if e.kimball_role == "dimension"]
    facts = [e for e in project.entities if e.kimball_role == "fact"]

    out.append("-- ========================================================")
    out.append("-- DDL Dimensional (Modelagem Kimball — Esquema Estrela)")
    out.append(f"-- Dialeto: {dialect.upper()}")
    out.append("-- ========================================================")
    if not dims and not facts:
        out.append("-- Nenhuma entidade foi classificada como Dimensão ou Fato.\n"
                   "-- Edite cada entidade (duplo-clique) e defina o 'Papel Dimensional (Kimball)'\n"
                   "-- como Dimensão ou Fato antes de gerar este DDL.")
        return "\n".join(out)
    out.append("")

    c.emit_domains(_used_domain_ids(project, dims + facts))

    out.append("-- ---------------- TABELAS DIMENSÃO ----------------")
    dim_sk_col = {}
    for d in dims:
        tbl, sk_col = f"dim_{s(d.name)}", f"{s(d.name)}_sk"
        dim_sk_col[d.id] = (tbl, sk_col)
        cols = [c.column(sk_col, identity_clause(dialect, map_type(dialect, "INTEGER")), True,
                         f"Chave substituta da dimensão {d.name}")]
        cons = []
        for col_name, col_type, nn, a, comment, src in _flatten_regular_attrs(c, d):
            cols.append(c.column(col_name, col_type, nn, comment))
            cons.extend(k for k in c.attr_constraints(tbl, col_name, src) if "UNIQUE" not in k)
        if d.scd_type == "scd2":
            for col_name, col_def in SCD2_COLUMNS.get(dialect, SCD2_COLUMNS["postgres"]):
                base_type = col_def.split(" NOT NULL")[0].split(" DEFAULT")[0]
                extra = col_def[len(base_type):].replace(" NOT NULL", "").strip()
                cols.append(c.column(col_name, base_type, " NOT NULL" in col_def or "NOT NULL" in col_def,
                                     SCD2_COMMENTS[col_name], extra=extra))
        scd_note = " (SCD Tipo 2 — mantém histórico de versões)" if d.scd_type == "scd2" \
            else " (SCD Tipo 1 — sobrescreve o valor atual)"
        c.create_table(tbl, cols, [f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({sk_col})"] + cons,
                       comment=_flat(d.description) or f"Dimensão {d.name}",
                       pre_comments=[f"-- Dimensão '{d.name}'{scd_note}"])

    out.append("-- ---------------- TABELAS FATO ----------------")
    for f in facts:
        tbl = f"fat_{s(f.name)}"
        sk = f"{s(f.name)}_sk"
        cols = [c.column(sk, identity_clause(dialect, map_type(dialect, "INTEGER")), True,
                         f"Chave substituta do fato {f.name}")]
        fk_cols = []
        rel_dim_pairs = []
        for r in project.rels:
            e1, e2 = project.find_entity(r.entity1_id), project.find_entity(r.entity2_id)
            if not e1 or not e2:
                continue
            if e1.id == f.id and e2.kimball_role == "dimension":
                rel_dim_pairs.append((r, e2))
            elif e2.id == f.id and e1.kimball_role == "dimension":
                rel_dim_pairs.append((r, e1))
        occurrences = {}
        for r, dim in rel_dim_pairs:
            occurrences.setdefault(dim.id, []).append(r)
        related, seen = [], set()
        for r, dim in rel_dim_pairs:
            if dim.id not in dim_sk_col:
                continue
            dim_tbl, sk_col = dim_sk_col[dim.id]
            # Role-playing dimension: mesma dimensão em vários relacionamentos -> FKs distintas
            fk_col = f"{s(r.name)}_{sk_col}" if len(occurrences[dim.id]) > 1 else sk_col
            if fk_col in seen:
                continue
            seen.add(fk_col)
            related.append(dim)
            cols.append(c.column(fk_col, map_type(dialect, "INTEGER"), True,
                                 f"FK para {dim_tbl}.{sk_col} (relacionamento {r.name})"))
            fk_cols.append((fk_col, dim_tbl, sk_col))
        measures = f.measure_attrs()
        cons = []
        for m in measures:
            col = s(m.name)
            cols.append(c.column(col, map_type(dialect, c.attr_type(m)), False,
                                 (c.comment_of(m) + " | " if c.comment_of(m) else "") + "Métrica"))
            cons.extend(k for k in c.attr_constraints(tbl, col, m) if "UNIQUE" not in k)
        measure_ids = {m.id for m in measures}
        for col_name, col_type, nn, a, comment, src in _flatten_regular_attrs(c, f):
            if a.id in measure_ids or a.is_pk:
                continue
            cols.append(c.column(col_name, col_type, nn, comment))
            cons.extend(k for k in c.attr_constraints(tbl, col_name, src) if "UNIQUE" not in k)
        constraints = [f"CONSTRAINT {c.cname('pk', tbl)} PRIMARY KEY ({sk})"]
        constraints += [f"CONSTRAINT {c.cname('fk', tbl, fk)} FOREIGN KEY ({fk}) REFERENCES {dt}({dsk})"
                        for fk, dt, dsk in fk_cols] + cons
        grain = ", ".join(dict.fromkeys(d.name for d in related)) or \
            "não identificada — relacione o fato às dimensões no diagrama"
        c.create_table(tbl, cols, constraints, comment=_flat(f.description) or f"Fato {f.name}",
                       pre_comments=[f"-- Fato '{f.name}' — grão definido pela combinação de: {grain}"])
        for fk, _dt, _dsk in fk_cols:
            out.append(index_stmt(dialect, tbl, [fk], c.cname("idx", tbl, fk)))
        out.append("")

    if dims and not facts:
        out.append("-- Nenhuma tabela Fato foi definida ainda — marque ao menos uma entidade como 'Fato'.")
    if facts and not dims:
        out.append("-- Nenhuma tabela Dimensão foi definida ainda — marque as entidades de contexto como 'Dimensão'.")
    return "\n".join(out)
